const STORE_KEY="wanderreads_store_v1";
const defaultBooks=[
{id:"b1",title:"Italy Travel Guide",author:"WanderReads Travel",category:"Travel Guides",price:799,oldPrice:999,rating:4.8,reviews:1200,badge:"Best Seller",created:10,search:"italy travel guide europe travel"},
{id:"b2",title:"Japan Travel Guide",author:"WanderReads Travel",category:"Travel Guides",price:749,oldPrice:999,rating:4.7,reviews:980,badge:"",created:9,search:"japan travel guide asia travel"},
{id:"b3",title:"New Zealand Travel Guide",author:"WanderReads Travel",category:"Travel Guides",price:799,oldPrice:1099,rating:4.8,reviews:760,badge:"New",created:15,search:"new zealand travel guide oceania"},
{id:"b4",title:"Switzerland Travel Guide",author:"WanderReads Travel",category:"Travel Guides",price:749,oldPrice:999,rating:4.6,reviews:642,badge:"",created:8,search:"switzerland travel guide europe"},
{id:"b5",title:"The Psychology of Money",author:"Morgan Housel",category:"Non-Fiction",price:399,oldPrice:499,rating:4.8,reviews:1400,badge:"Best Seller",created:7,search:"psychology money finance wealth nonfiction"},
{id:"b6",title:"Atomic Habits",author:"James Clear",category:"Self Help",price:449,oldPrice:699,rating:4.7,reviews:1500,badge:"Best Seller",created:6,search:"atomic habits self help productivity"},
{id:"b7",title:"Ikigai",author:"Héctor García",category:"Non-Fiction",price:399,oldPrice:599,rating:4.6,reviews:2100,badge:"",created:5,search:"ikigai japanese philosophy purpose nonfiction"},
{id:"b8",title:"Deep Work",author:"Cal Newport",category:"Self Help",price:449,oldPrice:699,rating:4.7,reviews:2200,badge:"",created:4,search:"deep work productivity focus self help"},
{id:"b9",title:"The Alchemist",author:"Paulo Coelho",category:"Fiction",price:299,oldPrice:399,rating:4.6,reviews:1900,badge:"",created:3,search:"alchemist fiction novel"},
{id:"b10",title:"The Midnight Library",author:"Matt Haig",category:"Fiction",price:499,oldPrice:699,rating:4.5,reviews:850,badge:"",created:14,search:"midnight library fiction novel"},
{id:"b11",title:"South Korea Travel Guide",author:"WanderReads Travel",category:"Travel Guides",price:749,oldPrice:999,rating:4.5,reviews:321,badge:"New",created:16,search:"south korea travel guide seoul asia"},
{id:"b12",title:"A Brief History of Time",author:"Stephen Hawking",category:"Non-Fiction",price:449,oldPrice:599,rating:4.7,reviews:1300,badge:"",created:2,search:"brief history time science physics nonfiction"}
];
const defaultState={books:defaultBooks,cart:{},wishlist:[],orders:[],subscribers:[],user:null};
let state=loadState();
let activeCategory="All";
let query="";
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));return saved?{...defaultState,...saved,books:saved.books?.length?saved.books:defaultBooks}:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function money(n){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n)}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function getBook(id){return state.books.find(b=>b.id===id)}
function cover(book,small=false){return `<div class="${small?"mini-cover":"cover-placeholder"}><span>${book.category.toUpperCase()}</span><strong>${book.title}</strong><small>${book.author}</small></div>`}
function categories(){return ["All",...new Set(state.books.map(b=>b.category))]}
function renderCategories(){const icons=["⌂","✦","▤","◌","◈","✎","◇"];$("#categoryGrid").innerHTML=categories().filter(c=>c!=="All").map((c,i)=>`<button class="category-card" data-category="${c}"><span class="category-icon">${icons[i%icons.length]}</span><h3>${c}</h3><p>${state.books.filter(b=>b.category===c).length} books to explore</p></button>`).join("")}
function renderFilters(){const tabs=categories();$("#filterTabs").innerHTML=tabs.map(c=>`<button class="${activeCategory===c?"active":""}" data-filter="${c}">${c}</button>`).join("")}
function filteredBooks(){let list=state.books.filter(b=>activeCategory==="All"||b.category===activeCategory);if(query)list=list.filter(b=>`${b.title} ${b.author} ${b.category} ${b.search}`.toLowerCase().includes(query));const sort=$("#sortSelect").value;if(sort==="price-low")list.sort((a,b)=>a.price-b.price);if(sort==="price-high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);if(sort==="newest")list.sort((a,b)=>b.created-a.created);return list}
function productCard(book){const wish=state.wishlist.includes(book.id);const discount=book.oldPrice?Math.round((1-book.price/book.oldPrice)*100):0;return `<article class="product-card"><div class="product-cover">${book.badge?`<span class="badge ${book.badge==="New"?"sale":""}">${book.badge}</span>`:""}<button class="wishlist ${wish?"active":""}" data-wishlist="${book.id}" aria-label="Wishlist ${book.title}">${wish?"♥":"♡"}</button>${cover(book)}</div><h3 title="${book.title}">${book.title}</h3><div class="author">${book.author}</div><div class="rating"><span>★★★★★</span> ${book.rating} (${book.reviews.toLocaleString("en-IN")})</div><div class="price-row"><span class="price">${money(book.price)}</span>${book.oldPrice?`<del class="old-price">${money(book.oldPrice)}</del><span class="discount">${discount}% off</span>`:""}</div><button class="add-cart" data-add="${book.id}">🛒 Add to Cart</button></article>`}
function renderProducts(){const list=filteredBooks();$("#productGrid").innerHTML=list.map(productCard).join("");$("#resultCount").textContent=`${list.length} ${list.length===1?"book":"books"}`;$("#emptyState").hidden=list.length!==0}
function renderNew(){const list=[...state.books].sort((a,b)=>b.created-a.created).slice(0,4);$("#newGrid").innerHTML=list.map(b=>`<article class="mini-card">${cover(b,true)}<div><strong>${b.title}</strong><small>${b.author}</small><span class="mini-price">${money(b.price)}</span></div></article>`).join("")}
function cartEntries(){return Object.entries(state.cart).map(([id,qty])=>({book:getBook(id),qty})).filter(x=>x.book&&x.qty>0)}
function cartTotal(){return cartEntries().reduce((sum,x)=>sum+x.book.price*x.qty,0)}
function renderCart(){const entries=cartEntries();$("#cartCount").textContent=entries.reduce((n,x)=>n+x.qty,0);$("#cartSubtotal").textContent=money(cartTotal());$("#checkoutTotal").textContent=money(cartTotal());$("#cartItems").innerHTML=entries.length?entries.map(x=>`<div class="cart-line">${cover(x.book,true)}<div class="line-info"><strong>${x.book.title}</strong><small>${money(x.book.price)} each</small><div class="qty"><button data-qty="${x.book.id}" data-change="-1">−</button><span>${x.qty}</span><button data-qty="${x.book.id}" data-change="1">+</button></div><button class="remove-line" data-remove="${x.book.id}">Remove</button></div><span class="line-total">${money(x.book.price*x.qty)}</span></div>`).join(""):`<div class="empty-state"><div>🛒</div><h3>Your cart is empty</h3><p>Add a few books and they will appear here.</p></div>`}
function renderWishlist(){const books=state.wishlist.map(getBook).filter(Boolean);$("#wishlistCount").textContent=books.length;$("#wishlistItems").innerHTML=books.length?books.map(b=>`<div class="wish-line">${cover(b,true)}<div class="line-info"><strong>${b.title}</strong><small>${b.author}</small><button class="add-cart" data-add="${b.id}">Add to Cart</button></div><button class="remove-line" data-wishlist="${b.id}">♥</button></div>`).join(""):`<div class="empty-state"><div>♡</div><h3>Your wishlist is empty</h3><p>Save books you want to come back to.</p></div>`}
function renderAll(){renderCategories();renderFilters();renderProducts();renderNew();renderCart();renderWishlist()}
function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;saveState();renderCart();toast("Book added to your cart")}
function toggleWishlist(id){state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];saveState();renderProducts();renderWishlist();toast(state.wishlist.includes(id)?"Added to wishlist":"Removed from wishlist")}
function openDrawer(id){$("#"+id).classList.add("open");$("#"+id).setAttribute("aria-hidden","false")}
function closeDrawer(id){$("#"+id).classList.remove("open");$("#"+id).setAttribute("aria-hidden","true")}
function openModal(id){$("#modalBackdrop").hidden=false;$("#"+id).hidden=false}
function closeModal(){$("#modalBackdrop").hidden=true;$$(".modal").forEach(m=>m.hidden=true)}
function accountView(){const user=state.user;$("#accountContent").innerHTML=user?`<div class="account-note"><strong>Signed in as ${user.name}</strong><br>${user.email}</div><div class="account-actions"><button class="btn btn-light" id="ordersBtn">My Orders</button><button class="btn btn-primary" id="logoutBtn">Sign out</button></div><div id="ordersList"></div>`:`<div class="account-tabs"><button class="active">Sign in</button><button disabled>Create account</button></div><form id="loginForm" class="form-grid"><label>Email<input name="email" type="email" required placeholder="you@example.com"></label><label>Password<input name="password" type="password" required placeholder="Password"></label><button class="btn btn-primary" type="submit">Sign in</button></form><p class="account-note">Demo mode: authentication is stored locally for now. Connect your database/auth provider later for real customer accounts.</p>`}
function openAccount(){accountView();openModal("accountModal")}
document.addEventListener("click",e=>{const cat=e.target.closest("[data-category]");if(cat){activeCategory=cat.dataset.category;renderFilters();renderProducts();$("#shop").scrollIntoView({behavior:"smooth"});return}const filter=e.target.closest("[data-filter]");if(filter){activeCategory=filter.dataset.filter;renderFilters();renderProducts();return}const add=e.target.closest("[data-add]");if(add){addToCart(add.dataset.add);return}const wish=e.target.closest("[data-wishlist]");if(wish){toggleWishlist(wish.dataset.wishlist);return}const q=e.target.closest("[data-qty]");if(q){const id=q.dataset.qty;state.cart[id]=(state.cart[id]||0)+Number(q.dataset.change);if(state.cart[id]<=0)delete state.cart[id];saveState();renderCart();return}const rem=e.target.closest("[data-remove]");if(rem){delete state.cart[rem.dataset.remove];saveState();renderCart();return}const close=e.target.closest("[data-close]");if(close){closeDrawer(close.dataset.close);return}const sort=e.target.closest("[data-sort]");if(sort){$("#sortSelect").value=sort.dataset.sort;renderProducts();$("#shop").scrollIntoView({behavior:"smooth"});return}});
$("#cartBtn").addEventListener("click",()=>{renderCart();openDrawer("cartDrawer")});
$("#wishlistBtn").addEventListener("click",()=>{renderWishlist();openDrawer("wishlistDrawer")});
$("#accountBtn").addEventListener("click",openAccount);
$("#sortSelect").addEventListener("change",renderProducts);
$("#clearFilters").addEventListener("click",()=>{query="";activeCategory="All";$("#searchInput").value="";$("#sortSelect").value="featured";renderAll()});
$("#searchForm").addEventListener("submit",e=>{e.preventDefault();query=$("#searchInput").value.trim().toLowerCase();activeCategory="All";renderFilters();renderProducts();$("#shop").scrollIntoView({behavior:"smooth"})});
$("#searchInput").addEventListener("input",e=>{query=e.target.value.trim().toLowerCase();activeCategory="All";renderFilters();renderProducts()});
$("#checkoutBtn").addEventListener("click",()=>{if(!cartEntries().length){toast("Your cart is empty");return}closeDrawer("cartDrawer");$("#checkoutTotal").textContent=money(cartTotal());openModal("checkoutModal")});
$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()});
$$(".modal-close").forEach(b=>b.addEventListener("click",closeModal));
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeDrawer("cartDrawer");closeDrawer("wishlistDrawer")}});
$("#checkoutForm").addEventListener("submit",e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const order={id:"WR-"+Date.now().toString().slice(-8),createdAt:new Date().toISOString(),customer:data,items:cartEntries().map(x=>({id:x.book.id,title:x.book.title,price:x.book.price,qty:x.qty})),total:cartTotal(),status:"Pending"};state.orders.push(order);state.cart={};saveState();e.currentTarget.reset();closeModal();renderAll();toast(`Order ${order.id} placed successfully`)});
$("#newsletterForm").addEventListener("submit",e=>{e.preventDefault();const email=$("#newsletterEmail").value.trim().toLowerCase();if(!state.subscribers.includes(email))state.subscribers.push(email);saveState();e.currentTarget.reset();toast("Thanks — you're subscribed!")});
$("#accountContent").addEventListener("submit",e=>{if(e.target.id!=="loginForm")return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));state.user={name:data.email.split("@")[0],email:data.email};saveState();accountView();toast("Signed in locally")});
$("#accountContent").addEventListener("click",e=>{if(e.target.id==="logoutBtn"){state.user=null;saveState();accountView();toast("Signed out")}if(e.target.id==="ordersBtn"){const list=$("#ordersList");list.innerHTML=state.orders.length?state.orders.slice().reverse().map(o=>`<div class="account-note" style="margin-top:10px"><strong>${o.id}</strong> · ${o.status}<br>${o.items.length} item(s) · ${money(o.total)}</div>`).join(""):`<p class="account-note">No orders yet.</p>`}});
renderAll();